# Generated by Django 3.0.3 on 2022-04-04 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('harji', models.ImageField(default='harji.jpeg', upload_to='profile_pics')),
                ('sai', models.ImageField(default='sai.jpeg', upload_to='profile_pics')),
                ('sandy', models.ImageField(default='sandy.jpeg', upload_to='profile_pics')),
                ('ak', models.ImageField(default='Ak.jpeg', upload_to='profile_pics')),
            ],
        ),
    ]
